[package]
name = "xylo"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.22"
clap = { version = "4.0.2", features = ["derive"] }
colored = "2.0.0"
nanoid = "0.4.0"
path-absolutize = "3.0.13"
serde = { version = "1.0.145", features = ["derive"] }
serde_yaml = "0.9.13"
