name: ci

on:
  - push

jobs:
  image:
    runs-on: ubuntu-latest
    if: ${{ success() && github.ref == 'refs/heads/master' }}

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - name: docker image
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          image_tag: ${{ github.run_number }}
